@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Diagrama de contexto da nova API-SITE

SHOW_PERSON_OUTLINE()

Person(customer, Desenvolvedor front-end, "Cliente principal, que consome a API")
System(apiSite, API-SITE, "Nova API que retorna dados dos cursos, disciplinas, professores, valores etc.")
System_Ext(educare, "Educare", "Sistema acadêmico legado monolítico.")

Rel(customer, apiSite, "Consome a API", "realiza as requisições HTTP para a api para alimentar o site")
Rel(educare, apiSite, "Replica os dados do sistema acadêmico para a api utilizando mensageria")
@enduml